/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type SiteSettingsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteSettings";
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type SoinsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "soinsPage";
};

export type YogaPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "yogaPage";
};

export type BreathworkPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "breathworkPage";
};

export type PilatesPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pilatesPage";
};

export type AboutPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aboutPage";
};

export type ContactPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contactPage";
};

export type LegalPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "legalPage";
};

export type PrestationsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "prestationsPage";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | SiteSettingsReference
    | HomePageReference
    | SoinsPageReference
    | YogaPageReference
    | BreathworkPageReference
    | PilatesPageReference
    | AboutPageReference
    | ContactPageReference
    | LegalPageReference
    | PrestationsPageReference;
  language?: string;
};

export type PrestationsPage = {
  _id: string;
  _type: "prestationsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  header?: {
    label?: string;
    h1?: string;
    intro?: string;
  };
  reserve?: string;
  categories?: Array<{
    title?: string;
    services?: Array<{
      name?: string;
      duration?: string;
      price?: string;
      description?: string;
      note?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  faqs?: Array<{
    q?: string;
    a?: RichText;
    _key: string;
  }>;
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  label?: string;
  titleLine1?: string;
  titleLine2?: string;
  sections?: Array<{
    title?: string;
    rows?: Array<{
      label?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  ipLabel?: string;
  ipBody?: string;
  dataLabel?: string;
  dataBodyHtml?: RichText;
  notFound?: {
    meta?: {
      title?: string;
      description?: string;
    };
    label?: string;
    titleLine1?: string;
    titleLine2?: string;
    body?: string;
    backHome?: string;
    navAria?: string;
    links?: Array<{
      path?: string;
      label?: string;
      _key: string;
    }>;
  };
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  header?: {
    label?: string;
    titleLine1?: string;
    titleLine2?: string;
  };
  form?: {
    label?: string;
    honeypot?: string;
    successTitle?: string;
    successText?: string;
    prenomLabel?: string;
    prenomPlaceholder?: string;
    nomLabel?: string;
    nomPlaceholder?: string;
    emailLabel?: string;
    emailPlaceholder?: string;
    pratiqueLabel?: string;
    pratiquePlaceholder?: string;
    messageLabel?: string;
    messagePlaceholder?: string;
    submit?: string;
  };
  booking?: {
    label?: string;
    eyebrow?: string;
    title?: string;
    text?: string;
    bgColor?: "blue" | "orange";
  };
  cabinet?: {
    label?: string;
    addressLine1?: string;
    addressLine2?: string;
    email?: string;
    hours1?: string;
    hours2?: string;
    hours3?: string;
  };
  map?: {
    label?: string;
    address?: string;
  };
  prose?: {
    label?: string;
    text?: RichText;
  };
  faqs?: Array<{
    q?: string;
    a?: RichText;
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  header?: {
    label?: string;
    titleLine1?: string;
    titleLine2?: string;
    subtitleHtml?: RichText;
    imgAlt?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  story?: {
    label?: string;
    lead?: string;
    body1?: string;
    body2?: string;
  };
  timeline?: {
    label?: string;
    items?: Array<{
      year?: string;
      event?: string;
      place?: string;
      _key: string;
    }>;
  };
  photos?: {
    image1?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt1?: string;
    image1Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    image2?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt2?: string;
    image2Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    image3?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt3?: string;
    image3Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    image4?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt4?: string;
    image4Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    image5?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt5?: string;
    image5Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    image6?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt6?: string;
    image6Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  quote?: {
    textHtml?: RichText;
    author?: string;
  };
  prose?: {
    label?: string;
    text?: RichText;
  };
  faqs?: Array<{
    q?: string;
    a?: RichText;
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PilatesPage = {
  _id: string;
  _type: "pilatesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  hero?: {
    label?: string;
    title?: string;
    quote?: string;
    sub?: string;
  };
  gallery?: {
    alt1?: string;
    image1?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    image1Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    alt2?: string;
    image2?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    image2Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    alt3?: string;
    image3?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    image3Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    videoBadge?: string;
    videoCaption?: string;
  };
  approach?: {
    label?: string;
    title?: string;
  };
  principles?: Array<{
    key?: string;
    title?: string;
    text?: string;
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  pricing?: {
    label?: string;
    titleHtml?: RichText;
    text?: string;
    bookArrow?: string;
    bgColor?: "blue" | "orange";
    rows?: Array<{
      key?: string;
      title?: string;
      detail?: string;
      price?: string;
      _key: string;
    }>;
  };
  prose?: {
    label?: string;
    text?: RichText;
  };
  faqs?: Array<{
    q?: string;
    a?: RichText;
    _key: string;
  }>;
  schema?: {
    name?: string;
    serviceType?: string;
    description?: string;
  };
};

export type BreathworkPage = {
  _id: string;
  _type: "breathworkPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  header?: {
    label?: string;
    title?: string;
    quote?: string;
    sub?: string;
  };
  gallery?: {
    photo1Alt?: string;
    photo1?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    photo1Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    photo2Alt?: string;
    photo2?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    photo2Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    photo3Alt?: string;
    photo3?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    photo3Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    videoBadge?: string;
    videoLabel?: string;
  };
  approach?: {
    label?: string;
    title?: string;
  };
  principles?: Array<{
    key?: string;
    title?: string;
    text?: string;
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  pricing?: {
    label?: string;
    titleHtml?: RichText;
    text?: string;
    book?: string;
    bgColor?: "blue" | "orange";
  };
  tarifs?: Array<{
    key?: string;
    title?: string;
    detail?: string;
    price?: string;
    _key: string;
  }>;
  prose?: {
    label?: string;
    text?: RichText;
  };
  faqs?: Array<{
    q?: string;
    a?: RichText;
    _key: string;
  }>;
  schema?: {
    name?: string;
    serviceType?: string;
    description?: string;
  };
};

export type YogaPage = {
  _id: string;
  _type: "yogaPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  header?: {
    label?: string;
    h1?: string;
    quote?: string;
    sub?: string;
  };
  photos?: {
    image1?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    image1Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    alt1?: string;
    image2?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    image2Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    alt2?: string;
    image3?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    image3Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    alt3?: string;
  };
  approche?: {
    label?: string;
    title?: string;
  };
  principles?: Array<{
    key?: string;
    title?: string;
    text?: string;
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  tarif?: {
    label?: string;
    titleLine1?: string;
    titleLine2?: string;
    body?: string;
    reserve?: string;
    bgColor?: "blue" | "orange";
    rows?: Array<{
      title?: string;
      detail?: string;
      price?: string;
      _key: string;
    }>;
  };
  prose?: {
    label?: string;
    text?: RichText;
  };
  faqs?: Array<{
    q?: string;
    a?: RichText;
    _key: string;
  }>;
  schema?: {
    name?: string;
    serviceType?: string;
    description?: string;
  };
};

export type SoinsPage = {
  _id: string;
  _type: "soinsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  header?: {
    label?: string;
    h1?: string;
    quote?: string;
    intro?: string;
    methodLabel?: string;
    sinceLabel?: string;
  };
  photo?: {
    oilTexture?: string;
    alt1?: string;
    alt2?: string;
    alt3?: string;
    image1?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    image1Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    image2?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    image2Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    image3?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    image3Video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  catalogue?: {
    label?: string;
    all?: string;
    reserve?: string;
  };
  soins?: Array<{
    key?: string;
    name?: string;
    sub?: string;
    price?: string;
    text?: string;
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  packagesLabel?: string;
  packagesBgColor?: "blue" | "orange";
  packages?: Array<{
    key?: string;
    name?: string;
    detail?: string;
    price?: string;
    save?: string;
    _key: string;
  }>;
  prose?: {
    label?: string;
    text?: RichText;
  };
  faqs?: Array<{
    q?: string;
    a?: RichText;
    _key: string;
  }>;
  schema?: {
    name?: string;
    serviceType?: string;
    description?: string;
    packagePrefix?: string;
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  hero?: {
    label?: string;
    titleLine1?: string;
    titleLine2?: string;
    sub?: string;
    footer?: string;
    imgAlt?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  welcome?: {
    label?: string;
    quote?: RichText;
    body1Html?: RichText;
    body2?: string;
    link?: string;
  };
  practices?: {
    label?: string;
    caption?: string;
    items?: Array<{
      key?: string;
      name?: string;
      desc?: string;
      icon?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      _key: string;
    }>;
  };
  cabinet?: {
    label?: string;
    titleLine1?: string;
    titleLine2?: string;
    body?: string;
    caption?: string;
    imgAlt?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    bgColor?: "blue" | "orange";
  };
  gallery?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    _key: string;
  }>;
  testimonials?: {
    label?: string;
    rating?: string;
    items?: Array<{
      quote?: string;
      author?: string;
      _key: string;
    }>;
  };
  prose?: {
    label?: string;
    text?: RichText;
  };
  faqs?: Array<{
    q?: string;
    a?: RichText;
    _key: string;
  }>;
  ctaBand?: {
    titleLine1?: string;
    titleLine2?: string;
    text?: string;
    bgColor?: "blue" | "orange";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  brand?: {
    logo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    logoWhite?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    portrait?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    gradient1?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    gradient2?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    circle?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    shapes?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  social?: {
    instagram?: string;
  };
  colors?: {
    blue?: string;
    orange?: string;
  };
  skipLink?: string;
  siteName?: string;
  nav?: {
    ariaLabel?: string;
    logoAria?: string;
    links?: {
      home?: string;
      soins?: string;
      yoga?: string;
      breathwork?: string;
      pilates?: string;
      about?: string;
      contact?: string;
    };
    cta?: string;
    menuOpen?: string;
    menuClose?: string;
    menuAria?: string;
    langAria?: string;
  };
  cta?: {
    book?: string;
    bookPlanity?: string;
  };
  footer?: {
    tagline?: string;
    colPractices?: string;
    colCabinet?: string;
    colFollow?: string;
    itinerary?: string;
    newsletter?: string;
    legal?: string;
    rights?: string;
  };
  breadcrumbHome?: string;
  faqTitle?: string;
  announcement?: {
    message?: string;
    linkLabel?: string;
    linkUrl?: string;
    variant?: "blue" | "orange";
  };
  schema?: {
    businessDescription?: string;
    personJobTitle?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | RichText
  | TranslationMetadata
  | InternationalizedArrayReference
  | SiteSettingsReference
  | HomePageReference
  | SoinsPageReference
  | YogaPageReference
  | BreathworkPageReference
  | PilatesPageReference
  | AboutPageReference
  | ContactPageReference
  | LegalPageReference
  | PrestationsPageReference
  | InternationalizedArrayReferenceValue
  | PrestationsPage
  | LegalPage
  | ContactPage
  | SanityImageAssetReference
  | SanityFileAssetReference
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | PilatesPage
  | BreathworkPage
  | YogaPage
  | SoinsPage
  | HomePage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;
